import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Google_Sans } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

const BodyFont = Inter({
  variable: "--font-google-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const HeaderFont = Google_Sans({
  variable: "--font-header",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const monospaceFont = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Moreshwar Dalavi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${HeaderFont.variable} ${BodyFont.variable} ${monospaceFont.className} antialiased`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
