import Head from "next/head";
import Image from "next/image";
import { socials } from "../utils/content";

import { useState } from "react";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Moreshwar Dalvi | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gradient-t from-[#fff] to-[#eee] tracking-wide px-10 md:px-20 lg:px-35 font-inter dark:bg-[#0f172a] dark:text-gray-50">
        {/* hero section start */}
        <section className="">

          <Navbar darkMode={darkMode} setDarkMode={ setDarkMode} />      

          <Hero />

          {/* social section start */}
          <div className="text-3xl flex justify-center gap-12 pt-9 py-5 text-gray-700 dark:text-purple-400">
            {socials.map((social) => (
              <div
                key={social.id}
                className="rounded-full shadow-md shadow-purple-400 p-3 cursor-pointer hover:scale-105 ease-in duration-300"
              >
                <a href={social.url} target="_blank" rel="noreferrer">
                  {social.icon}
                </a>
              </div>
            ))}
          </div>
          {/* social section end */}
        </section>
        {/* hero section end */}

        <About />

        <Skills />

        <Projects />

        
        <div className="w-full mx-auto py-4 flex justify-center text-gray-900 dark:text-slate-100 text-lg font-bold h-32">
          {/* social section start */}
          <div className="text-3xl flex justify-center gap-12 py-5 text-gray-700 dark:text-purple-400">
            {socials.map((social) => (
              <div
                key={social.id}
                className="rounded-full shadow-md shadow-purple-400 p-3 cursor-pointer hover:scale-105 ease-in duration-300"
              >
                <a href={social.url} target="_blank" rel="noreferrer">
                  {social.icon}
                </a>
              </div>
            ))}
          </div>
          {/* social section end */}
        </div>
      </main>
    </div>
  );
}
